/*
  # Add order_id Column to Tickets Table

  1. Purpose
    - Fix bug where order_id was being dynamically generated from reserved_at timestamp
    - This caused order_id reuse when reservations expired and new ones were created
    - Adding physical order_id column ensures each reservation gets a unique, persistent identifier

  2. Problem Being Solved
    - Multiple independent reservations were being grouped as one order in MyTicketsPage
    - When a reservation expired and user made a new reservation, the same order_id was generated
    - This happened because order_id was calculated as: campaign_id + '_' + EPOCH(reserved_at)
    - Updating reserved_at for expired tickets caused order_id collision

  3. Changes
    - Add order_id text column to tickets table (nullable for backward compatibility)
    - Create composite index on (campaign_id, order_id) for efficient order queries
    - Create index on order_id alone for direct lookups
    - Add helpful comment documenting the column's purpose

  4. Backward Compatibility
    - Column is nullable to support existing tickets without order_id
    - get_orders_by_phone function will be updated to handle both cases:
      * Use physical order_id when available (new tickets)
      * Fall back to generated order_id for legacy tickets (old tickets)

  5. Impact
    - All new reservations will store order_id persistently
    - Each reservation action gets a unique UUID that never changes
    - Expired reservations cannot cause order_id reuse
    - MyTicketsPage will correctly display separate orders for independent purchases
*/

-- Add order_id column to tickets table
-- This column stores the unique identifier for each order/reservation group
-- Generated by frontend (crypto.randomUUID()) and passed through the reservation flow
ALTER TABLE tickets
ADD COLUMN IF NOT EXISTS order_id text;

-- Create composite index for efficient order queries by campaign
-- This supports queries like "get all tickets for order X in campaign Y"
CREATE INDEX IF NOT EXISTS idx_tickets_campaign_order_id
ON tickets (campaign_id, order_id)
WHERE order_id IS NOT NULL;

-- Create index for direct order_id lookups
-- This supports queries like "get all tickets for order X across all campaigns"
CREATE INDEX IF NOT EXISTS idx_tickets_order_id
ON tickets (order_id)
WHERE order_id IS NOT NULL;

-- Add helpful comment
COMMENT ON COLUMN tickets.order_id IS
'Unique identifier for the order/reservation group. Generated by frontend as UUID and persisted to prevent order_id reuse when reservations expire. Each reservation action gets a unique order_id that never changes, ensuring correct order grouping in user interfaces.';
